// Each thing: { label, hours } — average hours required to complete (zero to done).
// Mix of small daily acts and large life-projects.
window.LASTCLOCK_THINGS = [
  { label: "books read", hoursEach: 8 },
  { label: "sunsets watched", hoursEach: 0.25 },
  { label: "cups of coffee drunk", hoursEach: 0.15 },
  { label: "meals eaten", hoursEach: 0.5 },
  { label: "nights of sleep", hoursEach: 8 },
  { label: "songs listened to", hoursEach: 0.06 },
  { label: "films watched", hoursEach: 1.9 },
  { label: "long walks taken", hoursEach: 1 },
  { label: "letters written", hoursEach: 0.5 },
  { label: "phone calls with your mother", hoursEach: 0.4 },
  { label: "dinners with friends", hoursEach: 2.5 },
  { label: "kisses given", hoursEach: 0.05 },
  { label: "marathons run", hoursEach: 600 },
  { label: "languages learned to fluency", hoursEach: 1500 },
  { label: "instruments mastered", hoursEach: 4000 },
  { label: "novels written", hoursEach: 1200 },
  { label: "businesses built", hoursEach: 12000 },
  { label: "summits of Everest", hoursEach: 1800 },
  { label: "PhDs earned", hoursEach: 9000 },
  { label: "houses built with your hands", hoursEach: 3500 },
  { label: "children raised to eighteen", hoursEach: 26280 },
  { label: "gardens planted and tended", hoursEach: 800 },
  { label: "countries visited", hoursEach: 120 },
  { label: "oceans swum across", hoursEach: 720 },
  { label: "paintings finished", hoursEach: 40 },
  { label: "symphonies composed", hoursEach: 2500 },
  { label: "marathons of solitude", hoursEach: 168 },
  { label: "times you learn to surf (zero to standing)", hoursEach: 30 },
  { label: "times you learn to ski (zero to confident)", hoursEach: 60 },
  { label: "chess ratings to master level", hoursEach: 6000 },
  { label: "weddings attended", hoursEach: 6 },
  { label: "funerals attended", hoursEach: 3 },
  { label: "first dates", hoursEach: 2 },
  { label: "swims in cold water", hoursEach: 0.3 },
  { label: "thunderstorms watched from a window", hoursEach: 0.5 },
  { label: "times you forgive someone fully", hoursEach: 24 },
  { label: "apologies you actually mean", hoursEach: 0.1 },
  { label: "haircuts", hoursEach: 0.5 },
  { label: "teeth brushed", hoursEach: 0.04 },
  { label: "loaves of bread baked", hoursEach: 4 },
  { label: "bottles of wine shared", hoursEach: 2 },
  { label: "naps taken", hoursEach: 0.5 },
  { label: "stars counted", hoursEach: 0.02 },
  { label: "deep conversations had", hoursEach: 3 },
  { label: "times you say 'i love you' and mean it", hoursEach: 0.01 },
  { label: "times you sit in silence", hoursEach: 0.5 },
  { label: "letters to your future self", hoursEach: 0.75 },
  { label: "rivers swum in", hoursEach: 1 },
  { label: "mountains climbed (any size)", hoursEach: 8 },
  { label: "campfires built", hoursEach: 1 },
  { label: "poems memorised", hoursEach: 4 },
  { label: "dances at weddings", hoursEach: 0.3 },
  { label: "times you watch the moon rise", hoursEach: 0.5 },
];
