// Each thing: { label, hoursEach } — average hours required to complete (zero to done).
// Mix of small daily acts and large life-projects.
export const THINGS = [
  { label: "books read", hoursEach: 8 },
  { label: "sunsets watched", hoursEach: 0.25 },
  { label: "cups of coffee drunk", hoursEach: 0.15 },
  { label: "cups of tea drunk", hoursEach: 0.15 },
  { label: "meals eaten", hoursEach: 0.5 },
  { label: "nights of sleep", hoursEach: 8 },
  { label: "songs listened to", hoursEach: 0.06 },
  { label: "albums listened to end-to-end", hoursEach: 0.75 },
  { label: "films watched", hoursEach: 1.9 },
  { label: "documentaries watched", hoursEach: 1.5 },
  { label: "long walks taken", hoursEach: 1 },
  { label: "letters written", hoursEach: 0.5 },
  { label: "love letters written", hoursEach: 1 },
  { label: "thank-you notes written", hoursEach: 0.25 },
  { label: "phone calls with your mother", hoursEach: 0.4 },
  { label: "times you see your parents while they are alive", hoursEach: 24 },
  { label: "dinners with friends", hoursEach: 2.5 },
  { label: "kisses given", hoursEach: 0.05 },
  { label: "marathons run", hoursEach: 400 },
  { label: "languages learned to fluency", hoursEach: 1500 },
  { label: "instruments mastered", hoursEach: 10000 },
  { label: "novels written", hoursEach: 1200 },
  { label: "novels re-read", hoursEach: 8 },
  { label: "businesses built", hoursEach: 12000 },
  { label: "summits of Everest", hoursEach: 2200 },
  { label: "PhDs earned", hoursEach: 9000 },
  { label: "houses built with your hands", hoursEach: 3500 },
  { label: "children raised to eighteen", hoursEach: 26280 },
  { label: "gardens planted and tended", hoursEach: 800 },
  { label: "vegetables grown to harvest", hoursEach: 80 },
  { label: "trees planted", hoursEach: 0.75 },
  { label: "countries visited", hoursEach: 120 },
  { label: "oceans swum across", hoursEach: 1500 },
  { label: "paintings finished", hoursEach: 40 },
  { label: "symphonies composed", hoursEach: 2500 },
  { label: "marathons of solitude", hoursEach: 168 },
  { label: "times you learn to surf (zero to standing)", hoursEach: 30 },
  { label: "times you learn to ski (zero to confident)", hoursEach: 60 },
  { label: "chess ratings to master level", hoursEach: 6000 },
  { label: "weddings attended", hoursEach: 6 },
  { label: "funerals attended", hoursEach: 3 },
  { label: "first dates", hoursEach: 2 },
  { label: "swims in cold water", hoursEach: 0.3 },
  { label: "wild swims", hoursEach: 0.5 },
  { label: "thunderstorms watched from a window", hoursEach: 0.5 },
  { label: "times you forgive someone fully", hoursEach: 24 },
  { label: "apologies you actually mean", hoursEach: 0.1 },
  { label: "haircuts", hoursEach: 0.5 },
  { label: "teeth brushed", hoursEach: 0.04 },
  { label: "loaves of bread baked", hoursEach: 4 },
  { label: "recipes you make your own", hoursEach: 8 },
  { label: "bottles of wine shared", hoursEach: 2 },
  { label: "naps taken", hoursEach: 0.5 },
  { label: "stars counted", hoursEach: 0.02 },
  { label: "stargazing nights", hoursEach: 1 },
  { label: "constellations memorised", hoursEach: 2 },
  { label: "deep conversations had", hoursEach: 3 },
  { label: "times you say 'i love you' and mean it", hoursEach: 0.01 },
  { label: "times you sit in silence", hoursEach: 0.5 },
  { label: "moments you sit with grief", hoursEach: 1 },
  { label: "letters to your future self", hoursEach: 0.75 },
  { label: "rivers swum in", hoursEach: 1 },
  { label: "mountains climbed (any size)", hoursEach: 8 },
  { label: "campfires built", hoursEach: 1 },
  { label: "fires watched die down", hoursEach: 0.5 },
  { label: "poems memorised", hoursEach: 4 },
  { label: "songs you learn to sing well", hoursEach: 5 },
  { label: "dances at weddings", hoursEach: 0.3 },
  { label: "times you watch the moon rise", hoursEach: 0.5 },
  { label: "times you watch the sunrise", hoursEach: 0.5 },
  { label: "early mornings outside before the world wakes", hoursEach: 1 },
  { label: "moments of awe", hoursEach: 0.05 },
  { label: "concerts attended", hoursEach: 3 },
  { label: "art galleries wandered through", hoursEach: 1.5 },
  { label: "museums lost in for an afternoon", hoursEach: 2.5 },
  { label: "yoga classes attended", hoursEach: 1.25 },
  { label: "morning meditations", hoursEach: 0.25 },
  { label: "ferries crossed", hoursEach: 1 },
  { label: "long train journeys", hoursEach: 6 },
  { label: "long drives alone after dark", hoursEach: 5 },
  { label: "old friendships rekindled", hoursEach: 6 },
  { label: "strangers helped", hoursEach: 0.5 },
  { label: "knots learned by hand", hoursEach: 0.5 },
  { label: "rooms you fall asleep in beside someone you love", hoursEach: 8 },
  { label: "books given away", hoursEach: 0.25 },
  { label: "glasses of water drunk", hoursEach: 0.05 },
  { label: "showers taken", hoursEach: 0.25 },
  { label: "handwritten journal entries", hoursEach: 0.5 },
  { label: "belly laughs", hoursEach: 0.05 },
  { label: "times you cry until you feel lighter", hoursEach: 0.5 },
  { label: "hands held in silence", hoursEach: 0.5 },
  { label: "lullabies sung", hoursEach: 0.1 },
  { label: "picnics on the grass", hoursEach: 2 },
  { label: "bicycle rides through a city", hoursEach: 1 },
  { label: "friendships that last a lifetime", hoursEach: 500 },
  { label: "homes you make truly yours", hoursEach: 800 },
  { label: "meals you cook for someone you love", hoursEach: 2 },
  { label: "birds learned to recognise on sight", hoursEach: 1.5 },
  { label: "journals filled cover to cover", hoursEach: 80 },
  { label: "photo albums you actually print", hoursEach: 8 },
  { label: "goodbyes to a beloved animal", hoursEach: 4 },
  { label: "pilgrimages walked on foot", hoursEach: 600 },
  { label: "silent retreats attended", hoursEach: 100 },
  { label: "boats sailed (zero to confident)", hoursEach: 200 },
  { label: "comets seen with your own eyes", hoursEach: 0.5 },
];
